openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /invoket24Enquiry:
    post:
      tags:
        - klik-esb-controller
      operationId: invoket24Enquiry
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Enquiry'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /greeting:
    get:
      tags:
        - greeting-controller
      operationId: greeting
      parameters:
        - name: name
          in: query
          required: false
          schema:
            type: string
            default: World
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Greeting'
components:
  schemas:
    Criterium:
      type: object
      properties:
        CriteriaName:
          type: string
        CriteriaOpr:
          type: string
        CriteriaVal:
          type: string
    Enquiry:
      type: object
      properties:
        EnquiryName:
          type: string
        UserInfo:
          $ref: '#/components/schemas/UserInfo'
        Criteria:
          type: array
          items:
            $ref: '#/components/schemas/Criterium'
    UserInfo:
      type: object
      properties:
        id:
          type: string
        password:
          type: string
    Greeting:
      type: object
      properties:
        id:
          type: integer
          format: int64
        content:
          type: string
